### ISSUE TITLE
все таки могу коммитить

### ISSUE THREAD

**Issue by gerrustalker** [SuperTemich2005/DDKG2#2]
или ты мне разрешил?))
![image](https://user-images.githubusercontent.com/45996315/115115198-b926b100-9f9b-11eb-8836-23158e48ca21.png)

**Comment by SuperTemich2005** [comment]
я разберусь с вопросом доступа к веткам, спасибо что заметил

**Comment by SuperTemich2005** [comment]
я, вероятно, исправил ситуацию

**Comment by gerrustalker** [comment]
ye
